{{- if eq .Values.deploymentType "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mcrouter.fullname" . }}
  labels:
    {{- include "mcrouter.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      {{- include "mcrouter.selectorLabels" . | nindent 6 }}
  {{- include "mcrouter.podTemplate" . | nindent 2 }}
{{- end }}
