{{- if and .Values.pdb.create (eq .Values.deploymentType "StatefulSet") -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mcrouter.fullname" . }}
  labels:
    {{- include "mcrouter.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "mcrouter.selectorLabels" . | nindent 6 }}
{{- end -}}
