apiVersion: v2
name: mcrouter
description: Mcrouter is a memcached protocol router for scaling memcached deployments.
type: application
version: 0.2.1
appVersion: "v2026.08.31.00"
home: https://github.com/dragoangel/mcrouter
icon: https://raw.githubusercontent.com/dragoangel/mcrouter/master/resources/logo.svg
sources:
  - https://github.com/dragoangel/mcrouter
  - https://github.com/facebook/mcrouter
maintainers:
  - name: dragoangel
    url: https://github.com/dragoangel
dependencies:
  - name: memcached
    version: 0.14.0
    repository: oci://registry-1.docker.io/cloudpirates
    condition: memcached.enabled
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: mcrouter
      image: ghcr.io/dragoangel/mcrouter:v2026.08.31.00
    - name: mcrouter_exporter
      image: ghcr.io/dev25/mcrouter_exporter:0.5.0
  artifacthub.io/links: |
    - name: source
      url: https://github.com/dragoangel/mcrouter
    - name: upstream
      url: https://github.com/facebook/mcrouter
    - name: exporter
      url: https://github.com/Dev25/mcrouter_exporter
