#!/usr/bin/env bash
# Regenerate build.deps.lock for a given mcrouter version.
#
# mcrouter's releases don't pin their Meta dependencies, so we lock each to its
# last commit at/before the mcrouter tag's commit timestamp (they ship in
# lockstep from Meta's monorepo). Run this whenever build.mcrouter.lock changes;
# the update-mcrouter-version workflow calls it automatically.
#
# Usage: scripts/build-deps-update-lock.sh [mcrouter-version]   (defaults to build.mcrouter.lock)
# Requires: curl, jq.
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
version="${1:-$(cat "$repo_root/build.mcrouter.lock")}"
api="https://api.github.com/repos"
auth=(); [ -n "${GITHUB_TOKEN:-}" ] && auth=(-H "Authorization: Bearer $GITHUB_TOKEN")

# Committer timestamp of the mcrouter tag; deps must be no newer than this.
ts="$(curl -fsSL "${auth[@]}" "$api/facebook/mcrouter/commits/$version" \
        | jq -r '.commit.committer.date')"
[ -n "$ts" ] && [ "$ts" != null ] || { echo "cannot resolve $version" >&2; exit 1; }

# Last commit of $1 (owner/repo) at/before the mcrouter tag timestamp.
resolve() {
  curl -fsSL "${auth[@]}" "$api/$1/commits?until=$ts&per_page=1" | jq -r '.[0].sha'
}

{
  echo "# Meta dependency commits pinned to mcrouter $version (tag committed $ts)."
  echo "# Generated by scripts/build-deps-update-lock.sh — do not edit by hand."
  echo "FOLLY_COMMIT=$(resolve facebook/folly)"
  echo "FBTHRIFT_COMMIT=$(resolve facebook/fbthrift)"
  echo "WANGLE_COMMIT=$(resolve facebook/wangle)"
  echo "FIZZ_COMMIT=$(resolve facebookincubator/fizz)"
  echo "MVFST_COMMIT=$(resolve facebook/mvfst)"
} > "$repo_root/build.deps.lock"

echo "Wrote build.deps.lock for mcrouter $version (deps @ $ts)"
